#theme: remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Code Crunch"
description: "Beat the clock, think fast, score high. Match the logos to score a point most points get the highest score on the leaderboard."
gitorg: "https://github.com/sreejagangapuram/Code-Crunch"
description: "Beat the clock, think fast, score high. Match the logos to score a point most points get the highest score on the leaderboard."
google_analytics:
# markdown: CommonMarkGhPages